server:
  port: 8082


spring:
  application:
    name: weather-service
  mvc:
    async:
      request-timeout: 120000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jakarta.persistence.validation.mode: none
        types:
          spatial:
            enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    # ????? ???????
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agro_plan}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      connect-timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 1
          max-wait: 1s

cache:
  weather-api:
    ttl-minutes: 60
    max-size: 2000
  seasonal-metrics:
    ttl-hours: 720   # 30 дней
    max-size: 5000

# Weather API Configuration
weather:
  api:
    forecast-base-url: https://api.open-meteo.com/v1
    historical-base-url: https://archive-api.open-meteo.com/v1
    max-in-memory-size: 10485760  # 10MB
    historical-data-lag-days: 5
    long-period-threshold-months: 13

logging:
  level:
    org:
      springframework:
        transaction: INFO
        transaction.interceptor: WARN
      orm:
        jpa: INFO
        jpa.JpaTransactionManager: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: WARN
    com:
      omstu:
        weatherservice: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:

    prefer-ip-address: true  # ???????????? IP ?????? hostname
    instance-id: ${spring.application.name}:${server.port}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches,metrics
  endpoint:
    health:
      show-details: when-authorized
